Add auto deployment and support for api routes path prefix (#2)
* Add autodeployment actions
  * with composite action
  * OIDC permissions
* Pin lambda docker platform/arch
* Add support for `path_prefix` for API endpoints
---------

Co-authored-by: Caden Helbling <caden.helbling@gmail.com>
Co-authored-by: Caden Helbling <63411686+Caden-Helbling@users.noreply.github.com>

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,10 +1,24 @@
 name: Pull Request - Lint and Test Workflow
 
+permissions:
+  id-token: write
+  contents: read
+
 on: [pull_request]
 
 jobs:
+  gitflow-enforcer:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'dev' || github.base_ref == 'production' && github.head_ref != 'main'
+        run: |
+          echo "ERROR: You can only merge to main from dev and to production from main"
+          exit 1
+
   lint:
     runs-on: ubuntu-latest
+    needs: [gitflow-enforcer]
     steps:
       - uses: actions/checkout@v3
       - name: Set up Python
@@ -31,10 +45,15 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
+          role-session-name: "ghgc-backend-github-action"
+          aws-region: "us-west-2"
+
       - name: Launch services
         run: |
-          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
-          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} \
           docker-compose up --build -d stac raster
 
       - name: Set up Python
@@ -67,9 +86,10 @@ jobs:
 
       - name: Stop services
         run: docker-compose stop
+
   predeploy:
     needs: [test]
-
+    environment: development
     runs-on: ubuntu-latest
     steps:
 
@@ -80,16 +100,16 @@ jobs:
           python-version: '3.9'
       
       - name: Setup Node
-        uses: actions/setup-node@v1
+        uses: actions/setup-node@v3
         with:
-          node-version: 17
+          node-version: 18
 
-      - name: Configure awscli
-        uses: aws-actions/configure-aws-credentials@v1
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-west-2
+          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
+          role-session-name: "ghgc-backend-github-action"
+          aws-region: "us-west-2"
 
       - uses: actions/cache@v3
         with:
@@ -109,10 +129,10 @@ jobs:
           python -m pip install --upgrade pip
           python -m pip install -e .[dev,deploy,test]
 
-      - name: Get dev environment configuration for develop branch
-        run: ./scripts/get-env.sh "veda-backend-uah-dev-env"
+      - name: Get environment configuration for develop branch
+        run: ./scripts/get-env.sh ${{ secrets.ENV_AWS_SECRET_NAME }}
 
       - name: Pre deployment CDK diff
         run: |
           echo $STAGE
-          cdk diff veda-backend-uah-dev
+          cdk diff --all
